### ISSUE TITLE
move sidebar definition to Widget.Menu

### ISSUE THREAD

**Issue by yari-dog** [yari-dog/hyprland-dotfiles#5]
automatically handles escape & clickoff events.
currently used in the quick settings toggles for logout

**Comment by yari-dog** [comment]
https://gjs-docs.gnome.org/gtk30~3.0/gtk.menu#method-popup_at_widget
https://gjs-docs.gnome.org/gtk30~3.0/gtk.menuitem
https://docs.gtk.org/gdk4/enum.Gravity.html

**Comment by yari-dog** [comment]
seems that maybe MenuItem is the only valid child of Menu, and using Box fucks with the spacing? for some reason?

**Comment by yari-dog** [comment]
nvm, Box should be fine, it's just an issue with ags (or gjs?) that cause menu_anchor to be ignored in the call to popup_at_widget

**Comment by yari-dog** [comment]
Don't think i'm gonna do this, as it would probably break other things. oh well.

**Comment by ghost** [comment]
u got this shit gang!
